motivational_quotes = {
    # Mental Toughness (30 quotes)
    "mental_toughness": [
        "Mental toughness is when you do it even when your brain screams stop.",
        "The mind quits 1000x before the body does.",
        "Discomfort is the price of admission to an extraordinary life.",
        "You don't get mental strength - you earn it through suffering.",
        "The best mental state? 'Fuck it, let's go.'",
        "Your worst day is someone else's dream workout.",
        "Pain is temporary. Quitting lasts forever.",
        "The voice that says 'you can't' is a liar. Prove it wrong.",
        "Champions are just people who refused to give up.",
        "When you want to quit, that's when the game begins.",
        "No one is coming to save you. Save yourself.",
        "The harder the grind, the brighter the shine.",
        "Tough times don't last. Tough people do.",
        "Pressure makes diamonds. Embrace the squeeze.",
        "The difference between ordinary and extraordinary is that little 'extra'.",
        "If it doesn't challenge you, it won't change you.",
        "The only easy day was yesterday.",
        "Sweat is just weakness leaving the body.",
        "You can either suffer the pain of discipline or the pain of regret.",
        "The body achieves what the mind believes.",
        "Excuses sound best to those who make them.",
        "The only limit is the one you set yourself.",
        "Get comfortable being uncomfortable.",
        "Winners do what losers won't.",
        "Your comfort zone is where dreams go to die.",
        "The burn means it's working.",
        "Don't stop when you're tired. Stop when you're done.",
        "The strongest steel is forged in the hottest fire.",
        "No resistance, no strength.",
        "The obstacle is the way."
    ],

    # Hustle & Grind (30 quotes)
    "hustle": [
        "While you're sleeping, someone's outworking you.",
        "Hustle beats talent when talent doesn't hustle.",
        "The grind doesn't stop. Neither should you.",
        "No days off isn't a slogan - it's a lifestyle.",
        "You either find a way or make one.",
        "The secret? Work while they sleep.",
        "Your 9-5 is someone else's warm-up.",
        "The extra mile is never crowded.",
        "Weekends are for amateurs.",
        "Burn the midnight oil while others burn time.",
        "Hustle in silence. Let success make the noise.",
        "Dreams don't work unless you do.",
        "The elevator to success is out of order. Take the stairs.",
        "Wake up with determination. Go to bed with satisfaction.",
        "Success is nothing more than a few simple disciplines, practiced every day.",
        "The only place success comes before work is in the dictionary.",
        "Grind now. Shine later.",
        "You'll never regret the work you did today.",
        "The difference between who you are and who you want to be is what you do.",
        "Small daily improvements lead to staggering long-term results.",
        "Don't watch the clock; do what it does. Keep going.",
        "The only thing standing between you and your goal is the story you keep telling yourself.",
        "Success isn't owned. It's leased. And rent is due every day.",
        "The road to success is always under construction.",
        "Opportunities don't happen. You create them.",
        "Work until your idols become your rivals.",
        "The only thing overworking leads to is more success.",
        "Your future is created by what you do today, not tomorrow.",
        "The grind is the glory.",
        "No one ever drowned in sweat.",
        "Sleep is a debt paid to weakness. The grind never stops.",
        "Your 9-to-5 is my warm-up.",
        "Weekends are for people with mediocre dreams.",
        "While you’re scrolling, I’m scaling.",
        "Hustle until your haters ask for a job referral.",
        "The only ‘off’ in my vocabulary is ‘takeoff’.",
        "Burn the midnight oil while others burn time.",
        "My comfort zone is a crime scene – I murdered it.",
        "Hustle beats talent when talent sleeps in.",
        "I don’t chase dreams. I execute them.",
        "The elevator to success is out of order. Take the stairs. Run them.",
        "My to-do list prays for mercy every morning.",
        "Sleep? That’s what coffins are for.",
        "I traded ‘maybe later’ for ‘watch me now’.",
        "My hustle is so loud, it drowns out my doubts.",
        "I don’t need luck – I create my own gravity.",
        "The grind doesn’t apologize for the shine.",
        "My hustle comes with a ‘Do Not Disturb’ sign.",
        "I put the ‘un’ in ‘unreasonable goals’.",
        "The only break I take is breaking limits.",
        "I don’t stop when I’m tired. I stop when I’m done.",
        "My hustle is my resume. My results are my references.",
        "I don’t believe in miracles. I believe in overtime.",
        "The world doesn’t pay for excuses. It pays for deliverables.",
        "I’m not a workaholic. I’m a work warrior.",
        "My hustle is my love language to success.",
        "I don’t wait for opportunities. I build them.",
        "The only ‘time out’ I know is when the clock runs out.",
        "I don’t compete. I dominate.",
        "Hustle now. Cry in your private jet later."
    ],

    # Success Principles (30 quotes)
    "success": [
        "Success leaves clues. Follow the patterns.",
        "The compound effect: Small actions, massive results.",
        "You're the average of the 5 people you tolerate.",
        "What you tolerate, you attract more of.",
        "Your network determines your net worth.",
        "Money flows to value. Create more value.",
        "The rich solve problems. The poor complain about them.",
        "Wealth isn't about money - it's about options.",
        "Opportunities multiply as they are seized.",
        "Profit is better than wages. Equity is better than both.",
        "Success is the sum of small efforts repeated daily.",
        "The secret of getting ahead is getting started.",
        "Don't wish it were easier. Wish you were better.",
        "The only thing worse than starting something and failing is not starting something.",
        "Successful people do what unsuccessful people are unwilling to do.",
        "Your level of success will rarely exceed your level of personal development.",
        "Success is walking from failure to failure with no loss of enthusiasm.",
        "The expert in anything was once a beginner.",
        "Success is not final, failure is not fatal: It is the courage to continue that counts.",
        "The only limit to our realization of tomorrow will be our doubts of today.",
        "Success usually comes to those who are too busy to be looking for it.",
        "The way to get started is to quit talking and begin doing.",
        "Success seems to be connected with action. Successful people keep moving.",
        "There are no shortcuts to any place worth going.",
        "Success is where preparation and opportunity meet.",
        "The successful warrior is the average man, with laser-like focus.",
        "Success is not the key to happiness. Happiness is the key to success.",
        "Successful people have fear, successful people have doubts, and successful people have worries.",
        "Success is getting what you want. Happiness is wanting what you get.",
        "The price of success is hard work, dedication to the job at hand."
    ],

    # Failure & Growth (30 quotes)
    "failure": [
        "Fail faster. Learn quicker.",
        "Every no gets you closer to a hell yes.",
        "Rejection is redirection.",
        "The master has failed more times than the beginner has tried.",
        "Your worst failures make the best stories.",
        "Scars prove you showed up to fight.",
        "Smooth seas don't make skilled sailors.",
        "If it doesn't challenge you, it won't change you.",
        "Breakdowns lead to breakthroughs.",
        "The obstacle is the way.",
        "Failure is simply the opportunity to begin again, this time more intelligently.",
        "I have not failed. I've just found 10,000 ways that won't work.",
        "Failure is the condiment that gives success its flavor.",
        "There is no failure except in no longer trying.",
        "Failure is not the opposite of success; it's part of success.",
        "Success is stumbling from failure to failure with no loss of enthusiasm.",
        "You build on failure. You use it as a stepping stone.",
        "The only real mistake is the one from which we learn nothing.",
        "Failure is the tuition you pay for success.",
        "Don't fear failure. Fear being in the exact same place next year.",
        "Failure is not fatal, but failure to change might be.",
        "Failure is only the opportunity to begin again more intelligently.",
        "Our greatest glory is not in never falling, but in rising every time we fall.",
        "A man's errors are his portals of discovery.",
        "You may encounter many defeats, but you must not be defeated.",
        "Failure is the opportunity to begin again more intelligently.",
        "The phoenix must burn to emerge.",
        "Every adversity, every failure, every heartache carries with it the seed of an equal or greater benefit.",
        "Rock bottom became the solid foundation on which I rebuilt my life.",
        "Sometimes you win, sometimes you learn."
    ],

    # Mindset Shifts (30 quotes)
    "mindset": [
        "Poverty is a mindset before it's a bank balance.",
        "Your income is directly tied to your self-image.",
        "What you walk past is what you accept.",
        "Victim mentality is the ultimate success killer.",
        "The moment you take full responsibility is when real growth begins.",
        "Excuses are the nails that build the house of failure.",
        "Your biggest limitation is the story you tell yourself.",
        "Confidence is earned through demonstrated competence.",
        "Self-doubt is the tax on dreams. Stop paying it.",
        "The only permission you need is your own.",
        "Whether you think you can or you think you can't, you're right.",
        "The mind is everything. What you think you become.",
        "Change your thoughts and you change your world.",
        "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
        "The only way to do great work is to love what you do.",
        "Your attitude, not your aptitude, will determine your altitude.",
        "The greatest discovery of all time is that a person can change his future by merely changing his attitude.",
        "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.",
        "Life is 10% what happens to you and 90% how you react to it.",
        "You cannot always control what goes on outside. But you can always control what goes on inside.",
        "The secret of change is to focus all of your energy, not on fighting the old, but on building the new.",
        "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
        "It's not the load that breaks you down, it's the way you carry it.",
        "You are never too old to set another goal or to dream a new dream.",
        "The only person you are destined to become is the person you decide to be.",
        "The greatest weapon against stress is our ability to choose one thought over another.",
        "Happiness is not something ready made. It comes from your own actions.",
        "The mind is not a vessel to be filled, but a fire to be kindled.",
        "You have power over your mind - not outside events. Realize this, and you will find strength.",
        "The happiness of your life depends upon the quality of your thoughts."
    ],

    # Warrior Mentality (30 quotes)
    "warrior": [
        "Warriors choose discipline over dopamine.",
        "The battle is won in the mind before it's fought in reality.",
        "A lion doesn't concern himself with the opinions of sheep.",
        "Iron sharpens iron. Surround yourself with killers.",
        "Weakness is a choice. Strength is earned.",
        "A warrior's rest comes after the victory, not before.",
        "The difference between a hero and coward is one decision.",
        "Fear is the compass pointing to where you must go.",
        "Comfort is the enemy of achievement.",
        "Suffer the pain of discipline or suffer the pain of regret.",
        "The warrior's greatest weapon is his mind.",
        "A warrior is not defined by his strength but by his resilience.",
        "The warrior's path is walked alone, but never lonely.",
        "A warrior's strength comes from overcoming what he thought he couldn't.",
        "The warrior knows that pain is temporary but quitting lasts forever.",
        "A true warrior fights not because he hates what is in front of him, but because he loves what is behind him.",
        "The warrior's creed: Never give up, never give in.",
        "A warrior's greatest battle is the one within.",
        "The warrior does not pray for an easy life, but for the strength to endure a difficult one.",
        "A warrior's spirit cannot be broken, only tempered.",
        "The warrior knows that fear is just a feeling, not a fact.",
        "A warrior's discipline is his freedom.",
        "The warrior understands that struggle is the path to mastery.",
        "A warrior's greatest enemy is not the opponent before him, but the doubt within him.",
        "The warrior's code: Honor, courage, commitment.",
        "A warrior does not seek conflict, but he does not fear it.",
        "The warrior's journey is not to defeat others, but to conquer himself.",
        "A warrior's rest is earned, not given.",
        "The warrior knows that every scar tells a story of survival.",
        "A warrior's legacy is not in the battles he won, but in the lives he inspired."
    ],

    # Business & Money (30 quotes)
    "business": [
        "Revenue solves all problems. Focus there first.",
        "Profitability = freedom. Losses = slavery.",
        "Business isn't complicated - create more value than you capture.",
        "The market doesn't care about your feelings. Deliver or die.",
        "Raise prices. Fire bad clients. Work less, earn more.",
        "Time poverty is worse than money poverty. Fix both.",
        "Wealth is created in leverage - time, money, or attention.",
        "Money follows speed. Execute faster.",
        "The best business strategy? Outlast everyone else.",
        "Monetize your knowledge. Package your experience.",
        "The best investment you can make is in yourself.",
        "Money is a great servant but a terrible master.",
        "The rich invest their time and money. The poor spend theirs.",
        "Formal education will make you a living; self-education will make you a fortune.",
        "The single most powerful asset we all have is our mind.",
        "It's not how much money you make, but how much money you keep.",
        "The more you learn, the more you earn.",
        "Opportunities are never lost; someone will take the ones you miss.",
        "The biggest risk is not taking any risk.",
        "Price is what you pay. Value is what you get.",
        "The stock market is a device for transferring money from the impatient to the patient.",
        "Risk comes from not knowing what you're doing.",
        "The most important investment you can make is in yourself.",
        "Never depend on single income. Make investment to create a second source.",
        "If you don't find a way to make money while you sleep, you will work until you die.",
        "The goal isn't more money. The goal is living life on your terms.",
        "Money is only a tool. It will take you wherever you wish, but it will not replace you as the driver.",
        "Financial peace isn't the acquisition of stuff. It's learning to live on less than you make.",
        "An investment in knowledge pays the best interest.",
        "The art is not in making money, but in keeping it."
    ],

    # Life Truths (30 quotes)
    "life": [
        "No one cares. Produce results anyway.",
        "The universe rewards boldness.",
        "Your life is the sum of your standards.",
        "What you avoid controls you.",
        "Character is what you do when no one's watching.",
        "Legacy > Likes.",
        "Hard choices, easy life. Easy choices, hard life.",
        "The price of anything is the life you exchange for it.",
        "Time is the only non-renewable resource. Spend it wisely.",
        "Death is coming. What will you have to show for your time here?",
        "Life is 10% what happens to you and 90% how you react to it.",
        "The purpose of our lives is to be happy.",
        "Life is what happens when you're busy making other plans.",
        "Get busy living or get busy dying.",
        "You only live once, but if you do it right, once is enough.",
        "The unexamined life is not worth living.",
        "Turn your wounds into wisdom.",
        "Live as if you were to die tomorrow. Learn as if you were to live forever.",
        "The two most important days in your life are the day you are born and the day you find out why.",
        "Life is not a problem to be solved, but a reality to be experienced.",
        "The best way to predict your future is to create it.",
        "Life is really simple, but we insist on making it complicated.",
        "The biggest adventure you can take is to live the life of your dreams.",
        "Life shrinks or expands in proportion to one's courage.",
        "Don't count the days, make the days count.",
        "Life is either a daring adventure or nothing at all.",
        "The good life is one inspired by love and guided by knowledge.",
        "Life isn't about finding yourself. Life is about creating yourself.",
        "The meaning of life is to give life meaning.",
        "Life is short, and it's up to you to make it sweet."
    ],

    # Discipline (30 quotes)
    "discipline": [
        "Discipline is choosing between what you want now and what you want most.",
        "Discipline is the bridge between goals and accomplishment.",
        "With self-discipline most anything is possible.",
        "Discipline is doing what needs to be done even when you don't want to do it.",
        "Small disciplines repeated with consistency every day lead to great achievements.",
        "Discipline is the soul of an army. It makes small numbers formidable.",
        "The pain of discipline weighs ounces. The pain of regret weighs tons.",
        "Discipline is remembering what you want.",
        "Discipline is the foundation upon which all success is built.",
        "Without discipline, there's no life at all.",
        "Discipline is the refining fire by which talent becomes ability.",
        "Discipline is the difference between wishing for something and getting it.",
        "Self-discipline begins with the mastery of your thoughts.",
        "Discipline is the mother of good fortune.",
        "Discipline is the strongest form of self-love.",
        "Discipline is the key to unlocking your potential.",
        "Discipline is the habit of taking consistent action.",
        "Discipline is the compass that guides you to your goals.",
        "Discipline is the art of making yourself do what you know needs to be done.",
        "Discipline is the fuel for achievement.",
        "Discipline is the root of all virtues.",
        "Discipline is the soul of success.",
        "Discipline is the master key to riches.",
        "Discipline is the ability to make yourself do what you should do, when you should do it.",
        "Discipline is the difference between a dream and a goal.",
        "Discipline is the path to freedom.",
        "Discipline is the secret ingredient to success.",
        "Discipline is the ability to give up excuses.",
        "Discipline is the strength to resist temptations.",
        "Discipline is the power to say no to distractions."
    ],

    # motivational_quotes (30 quotes)
    "motivational_quotes": [
        "motivational_quotes is what gets you started. Habit is what keeps you going.",
        "People often say that motivational_quotes doesn't last. Well, neither does bathing - that's why we recommend it daily.",
        "The only way to do great work is to love what you do.",
        "Your time is limited, so don't waste it living someone else's life.",
        "The future belongs to those who believe in the beauty of their dreams.",
        "The only limit to our realization of tomorrow is our doubts of today.",
        "Don't watch the clock; do what it does. Keep going.",
        "You miss 100% of the shots you don't take.",
        "The secret of getting ahead is getting started.",
        "Believe you can and you're halfway there.",
        "It always seems impossible until it's done.",
        "Start where you are. Use what you have. Do what you can.",
        "The best way to predict the future is to create it.",
        "Success is not the key to happiness. Happiness is the key to success.",
        "The only person you are destined to become is the person you decide to be.",
        "What you get by achieving your goals is not as important as what you become by achieving your goals.",
        "You are never too old to set another goal or to dream a new dream.",
        "The journey of a thousand miles begins with one step.",
        "Dream big and dare to fail.",
        "You don't have to be great to start, but you have to start to be great.",
        "The only thing standing between you and your goal is the story you keep telling yourself.",
        "Success is walking from failure to failure with no loss of enthusiasm.",
        "The expert in anything was once a beginner.",
        "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
        "The harder you work for something, the greater you'll feel when you achieve it.",
        "Push yourself, because no one else is going to do it for you.",
        "Great things never come from comfort zones.",
        "Dream it. Believe it. Build it.",
        "The secret to getting ahead is getting started.",
        "Don't stop when you're tired. Stop when you're done."
    ],
    
    "achievement": [
        "You made it through struggles and mental fights. Enjoy this glory!",
        "Success isn’t luck—it’s proof of your persistence. Celebrate!",
        "The world rewards those who refuse to quit. Today, it rewarded YOU.",
        "From ‘I can’t’ to ‘I did’—that’s the power of your hustle.",
        "You didn’t just reach the goal—you redefined what’s possible.",
        "Behind this win are sleepless nights no one saw. Salute to you!",
        "Victory tastes sweetest after the hardest battles. Cheers!",
        "You turned ‘impossible’ into ‘I’m possible’. Legendary.",
        "Now that you’re here, look back and admire how far you’ve come.",
        "This is not the end—it’s the launchpad for your next level.",
        "They said you couldn’t. You said ‘watch me’. And you did.",
        "Your success is a middle finger to doubters. Keep rising.",
        "You didn’t just succeed—you inspired others to try harder.",
        "The grind paid off. Now, enjoy the view from the top.",
        "You didn’t wait for a hero. You became one.",
        "From dreams to reality—because you put in the work.",
        "Your perseverance just wrote a success story. Chapter one.",
        "You didn’t just cross the finish line—you owned it.",
        "The universe applauds those who dare. Take a bow.",
        "This win? Just a preview of what’s coming next.",
        "You turned pressure into diamonds. Now shine.",
        "Success didn’t find you—you chased it down.",
        "You didn’t just achieve—you set a new standard.",
        "The obstacle was the way. And you walked it.",
        "You didn’t wait for motivation. You created it.",
        "Your discipline just cashed a check. Spend it proudly.",
        "You didn’t just climb the mountain—you brought others with you.",
        "The goal was just an excuse to become who you are now.",
        "You didn’t just win—you proved what’s possible.",
        "This is your moment. Own it."
    ],
    
    "positivity": [
        "Gratitude turns what you have into enough.",
        "The sun doesn’t apologize for shining. Don’t you either.",
        "Your vibe attracts your tribe. Stay positive.",
        "Happiness is a choice—make it daily.",
        "The best way to predict the future is to create it—with joy.",
        "You’re not stuck. You’re just preparing for a leap.",
        "Negative thoughts can’t survive in a grateful mind.",
        "Today is a gift. That’s why it’s called the present.",
        "You’re not falling behind. Your path is unique.",
        "The more you praise life, the more life praises you.",
        "Smile—it’s free therapy.",
        "Your attitude is like a price tag. How much are you worth?",
        "Every day may not be good, but there’s good in every day.",
        "You’re not waiting for the storm to pass—you’re learning to dance in the rain.",
        "Positivity isn’t ignoring problems. It’s solving them with hope.",
        "The world needs your light. Don’t dim it.",
        "You’re not broken. You’re becoming.",
        "Gratitude is the healthiest human emotion. Practice it.",
        "Your energy introduces you before you speak. Make it bold.",
        "Joy is resistance. Choose it.",
        "You’re not a drop in the ocean. You’re the entire ocean in a drop.",
        "The universe fights for those who stay hopeful.",
        "You’re not lost. You’re exploring.",
        "Happiness isn’t ‘out there’. It’s within you.",
        "Your mind is a garden. Plant flowers, not weeds.",
        "Optimism is a superpower. Wear it.",
        "You’re not failing—you’re collecting data for success.",
        "The best revenge is massive success—and a happy heart.",
        "You’re not alone. The stars root for you too.",
        "Today’s ‘I’ll try’ is tomorrow’s ‘I did’."
    ],
    
    "resilience": [
        "Rock bottom became the foundation you rebuilt yourself on.",
        "You’re not starting over—you’re starting wiser.",
        "The comeback is always stronger than the setback.",
        "You didn’t lose. You learned.",
        "Scars are proof you fought battles and survived.",
        "The phoenix must burn to rise. You’re on fire.",
        "You’re not broken—you’re being reshaped.",
        "Fall seven times, stand up eight. This is your stand.",
        "Your struggles are the setup for your comeback story.",
        "The wound is where the light enters you.",
        "You’re not a failure—you’re a work in progress.",
        "The strongest steel is forged in the hottest fire.",
        "You’re not stuck. You’re gathering momentum.",
        "Your lowest moments prepare you for highest victories.",
        "The caterpillar thought it was the end. Then it became a butterfly.",
        "You’re not falling apart—you’re falling into place.",
        "The darkest nights produce the brightest stars.",
        "You’re not defeated—you’re being redirected.",
        "Your pain is the soil for your growth.",
        "The universe doesn’t test you—it prepares you.",
        "You’re not losing—you’re leveling up.",
        "The harder the fall, the grander the ascent.",
        "You’re not a victim—you’re a survivor.",
        "The storm is just clearing the path for your sunshine.",
        "You’re not behind—you’re being recalibrated.",
        "The breakdown is the prelude to the breakthrough.",
        "You’re not quitting—you’re pivoting.",
        "The struggle is the birthplace of strength.",
        "You’re not losing time—you’re gaining wisdom.",
        "The comeback starts now."
    ],
    
    "self_improvement": [
        "Every day is a new opportunity to improve yourself.",
        "You are your only limit. Break those barriers.",
        "Self-improvement is a journey, not a destination.",
        "The only person you should try to be better than is the person you were yesterday.",
        "Invest in yourself. It pays the best interest.",
        "Small daily improvements are key to staggering long-term results.",
        "You don’t have to be great to start, but you have to start to be great.",
        "Your life does not get better by chance, it gets better by change.",
        "The only way to do great work is to love what you do.",
        "Success is not for the lazy. Get up and grind.",
        "You are what you repeatedly do. Excellence, then, is not an act, but a habit.",
        "The future depends on what you do today.",
        "Self-improvement is the key to unlocking your potential.",
        "You can’t improve what you don’t measure. Track your progress.",
        "The best project you will ever work on is yourself.",
        "Your mindset determines your success. Cultivate a growth mindset.",
        "You are the architect of your own destiny. Build wisely.",
        "Every accomplishment starts with the decision to try.",
        "Don’t wait for opportunity. Create it through self-improvement.",
        "Your only competition is who you were yesterday.",
        "Self-improvement is not a sprint; it’s a marathon. Pace yourself.",
        "You can’t change your past, but you can shape your future through self-improvement.",
        "The more you learn, the more you earn. Invest in knowledge.",
        "Your habits shape your life. Make them count.",
        "Self-improvement is about progress, not perfection.",
        "You are capable of more than you know. Push your limits.",
        "The best investment you can make is in yourself and your growth.",
        "Self-improvement is the path to personal freedom and fulfillment."
    ],
    
    "focus": [
        "Distraction is the enemy of legacy. Stay focused.",
        "The ones who focus win.",
        "Your focus determines your reality.",
        "Small daily focus beats occasional hustle.",
        "Concentration is the secret of strength.",
        "The more you focus, the luckier you get.",
        "Focus is saying no to 1,000 good ideas.",
        "Depth over breadth. Mastery over dabblings.",
        "The shorter your to-do list, the sharper your focus.",
        "Focus is the art of ignoring the unimportant.",
        "You can’t climb mountains if you’re distracted by pebbles.",
        "Laser focus creates extraordinary results.",
        "The difference between ordinary and extraordinary? Focus.",
        "Multitasking is for mediocre results.",
        "Focus is the gateway to flow.",
        "One goal at a time. One step at a time.",
        "The distracted mind is a wasted mind.",
        "Focus is the antidote to overwhelm.",
        "The more you concentrate, the more you accomplish.",
        "Your focus is your superpower.",
        "The world’s noise can’t compete with your focus.",
        "Deep work creates deep impact.",
        "Focus isn’t about time. It’s about priorities.",
        "The focused mind is the creative mind.",
        "Attention is currency. Spend it wisely.",
        "Focus turns effort into excellence.",
        "The secret to productivity? Single-tasking.",
        "Focus is the bridge between goals and success.",
        "The more you ignore distractions, the more success finds you.",
        "Focus like your future depends on it—because it does."
    ],
    
    "leadership": [
        "Leadership isn’t a title. It’s action.",
        "The best leaders lift others while climbing.",
        "Your influence is your legacy.",
        "Leadership is solving problems, not blaming.",
        "A leader’s job is to create more leaders.",
        "People won’t follow you for your plan—they’ll follow you for your passion.",
        "Leadership is about making others better.",
        "The mark of a leader? Empowered teams.",
        "True leadership serves, not controls.",
        "Leadership isn’t being in charge. It’s taking care of those in your charge.",
        "The best leaders are the best listeners.",
        "Leadership is turning vision into reality.",
        "A leader’s strength is their team’s strength.",
        "Leadership is the art of making hard things simple.",
        "You don’t need permission to lead.",
        "Leadership is courage in action.",
        "The best leaders lead by example—silently.",
        "Leadership isn’t about being liked. It’s about being respected.",
        "A leader’s job is to see potential before others do.",
        "Leadership is the ability to inspire action.",
        "Great leaders don’t create followers. They create more leaders.",
        "Leadership is the difference between ‘I’ and ‘we’.",
        "The best leaders are the most accountable.",
        "Leadership is about lighting fires, not filling buckets.",
        "A leader’s attitude becomes their team’s attitude.",
        "Leadership is the art of making others believe in themselves.",
        "The best leaders are the most decisive.",
        "Leadership is the ability to navigate uncertainty.",
        "A leader’s legacy is measured by impact, not income.",
        "Leadership starts when you take responsibility."
    ],
    
    "love": [
        "Love is not about finding the perfect person, but about seeing an imperfect person perfectly.",
        "The best thing to hold onto in life is each other.",
        "Self-love is the foundation for every other love.",
        "A strong relationship requires choosing each other every day.",
        "Love is a verb. It’s not just a feeling—it’s action.",
        "The greatest happiness is to love and be loved in return.",
        "Love doesn’t make the world go round. Love is what makes the ride worthwhile.",
        "You don’t love someone for their looks, but for the way they make your soul feel.",
        "Love is when the other person’s happiness is more important than your own.",
        "The best relationships are built on trust, respect, and endless inside jokes.",
        "Love is the bridge between two hearts.",
        "A true relationship is when you can tell each other anything and everything.",
        "Love isn’t about possession. It’s about appreciation.",
        "The best love is the kind that awakens the soul.",
        "Love is friendship set on fire.",
        "You know it’s love when all you want is for them to be happy.",
        "Love is the only force capable of transforming an enemy into a friend.",
        "The best love stories don’t have endings—they have new beginnings.",
        "Love is giving someone the power to destroy you, but trusting them not to.",
        "Love is the language every heart understands.",
        "A heart that loves is always young.",
        "Love is the master key that opens the gates of happiness.",
        "Love doesn’t need reasons. It just needs a chance.",
        "The best love is the one that makes you a better person.",
        "Love is the only gold.",
        "Love is the greatest refreshment in life.",
        "Love is the flower you’ve got to let grow.",
        "Love is the triumph of imagination over intelligence.",
        "Love is the poetry of the senses.",
        "Love is the answer, and you know that for sure."
    ],
    
    "fitness": [
        "Strength doesn’t come from what you can do. It comes from overcoming what you couldn’t.",
        "Your body hears everything your mind says. Stay positive.",
        "The only bad workout is the one you didn’t do.",
        "Discipline is choosing between what you want now and what you want most.",
        "Fitness is not about being better than someone else. It’s about being better than you used to be.",
        "The pain you feel today will be the strength you feel tomorrow.",
        "Success starts with self-discipline. It starts with you.",
        "Your health is an investment, not an expense.",
        "The body achieves what the mind believes.",
        "Don’t stop when you’re tired. Stop when you’re done.",
        "Sweat is just fat crying.",
        "You don’t have to be extreme, just consistent.",
        "The hardest part is getting started. The rest is just sweat.",
        "Fitness is 10% inspiration and 90% perspiration.",
        "You are one workout away from a good mood.",
        "Strive for progress, not perfection.",
        "The only limit is the one you set yourself.",
        "It’s not about having time. It’s about making time.",
        "Train like a beast, look like a beauty.",
        "Your future self will thank you for starting today.",
        "The secret of getting ahead is getting started.",
        "You don’t get the body you dream of. You get the body you work for.",
        "Strong is the new skinny.",
        "The only bad workout is the one that didn’t happen.",
        "Fitness is not a destination. It’s a way of life.",
        "You don’t have to go fast. You just have to go.",
        "The difference between try and triumph is a little ‘umph’.",
        "The only person you are destined to become is the person you decide to be.",
        "The only workout you regret is the one you skipped.",
        "Every rep counts."
    ],
    
    "creativity": [
        "Creativity is intelligence having fun.",
        "The worst enemy to creativity is self-doubt.",
        "You can’t use up creativity. The more you use, the more you have.",
        "Creativity takes courage.",
        "Innovation distinguishes between a leader and a follower.",
        "The creative adult is the child who survived.",
        "Creativity is piercing the mundane to find the marvelous.",
        "Do something today that your future self will thank you for.",
        "Creativity is allowing yourself to make mistakes. Art is knowing which ones to keep.",
        "The world always seems brighter when you’ve just made something that wasn’t there before.",
        "Creativity is seeing what everyone else has seen and thinking what no one else has thought.",
        "The desire to create is one of the deepest yearnings of the human soul.",
        "Creativity is the way I share my soul with the world.",
        "You don’t need to be great to start, but you need to start to be great.",
        "Creativity is contagious. Pass it on.",
        "The only limit to creativity is the imagination.",
        "Creativity is the power to connect the seemingly unconnected.",
        "The artist is nothing without the gift, but the gift is nothing without work.",
        "Creativity is the greatest rebellion in existence.",
        "Every artist was first an amateur.",
        "Creativity is inventing, experimenting, growing, taking risks, breaking rules, making mistakes, and having fun.",
        "The creative process is a process of surrender, not control.",
        "Creativity is the key to success in the future.",
        "The best ideas come as jokes. Make your thinking as funny as possible.",
        "Creativity is the ability to see possibilities where others see problems.",
        "The creative mind plays with the objects it loves.",
        "Creativity is the soul’s rebellion against the mundane.",
        "The only way to do great work is to love what you do.",
        "Creativity is the spark that ignites innovation.",
        "The world needs your unique voice. Don’t silence it."
    ],
    
    "adventure": [
        "Adventure is worthwhile in itself.",
        "The biggest adventure you can take is to live the life of your dreams.",
        "Life is either a daring adventure or nothing at all.",
        "Adventure is not outside man; it is within.",
        "The world is a book, and those who do not travel read only one page.",
        "Adventure is the best way to learn.",
        "To travel is to live.",
        "Adventure is out there!",
        "Life begins at the end of your comfort zone.",
        "Adventure is the juice of life.",
        "The best view comes after the hardest climb.",
        "Adventure is calling, and I must go.",
        "Not all those who wander are lost.",
        "Adventure is the only way to escape the ordinary.",
        "Travel far, travel wide, travel with an open heart.",
        "Adventure is the best teacher.",
        "The journey, not the arrival, matters.",
        "Adventure is the spice of life.",
        "Go where you feel most alive.",
        "Adventure is the best way to find yourself.",
        "The world is too big to stay in one place.",
        "Adventure is the best investment.",
        "Life is short, and the world is wide.",
        "Adventure is the best medicine.",
        "The best stories come from adventures.",
        "Adventure is the best way to grow.",
        "The best memories come from adventures.",
        "Adventure is the best way to live.",
        "The best life is a collection of adventures.",
        "Adventure is the best way to love."
    ],
    
    "technology": [
        "The best way to predict the future is to invent it.",
        "Technology is best when it brings people together.",
        "The future belongs to those who believe in the beauty of their dreams.",
        "The only way to discover the limits of the possible is to go beyond them into the impossible.",
        "The future is already here—it’s just not evenly distributed.",
        "Technology is a tool, not a destination.",
        "The future is not something we enter. The future is something we create.",
        "The best way to predict the future is to create it.",
        "The future is not a gift. It is an achievement.",
        "The future is not something we wait for. It is something we build.",
        "The future is not a place we are going to, but a place we are creating.",
        "The future is not a dream. It is a reality.",
        "The future is not a mystery. It is a possibility.",
        "The future is not a destination. It is a journey.",
        "The future is not a problem to be solved. It is an opportunity to be seized.",
        "The future is not a threat. It is a promise.",
        "The future is not a challenge. It is a gift.",
        "The future is not a burden. It is a blessing.",
        "The future is not a risk. It is a reward.",
        "The future is not a fear. It is a hope.",
        "The future is not a doubt. It is a certainty.",
        "The future is not a question. It is an answer.",
        "The future is not a worry. It is a wonder.",
        "The future is not a regret. It is a joy.",
        "The future is not a loss. It is a gain.",
        "The future is not a failure. It is a success.",
        "The future is not a mistake. It is a miracle.",
        "The future is not a curse. It is a blessing.",
        "The future is not a nightmare. It is a dream.",
        "The future is not a tragedy. It is a triumph."
    ],
    
    "spirituality": [
        "Peace comes from within. Do not seek it without.",
        "The quieter you become, the more you can hear.",
        "Spirituality is not about religion. It’s about connection.",
        "The soul always knows what to do to heal itself. The challenge is to silence the mind.",
        "Spirituality is the art of keeping your inner fire alive.",
        "The best way to find yourself is to lose yourself in the service of others.",
        "Spirituality is not a luxury. It’s a necessity.",
        "The greatest prayer is patience.",
        "Spirituality is the journey of the self, through the self, to the self.",
        "The more you know yourself, the more you know the universe.",
        "Spirituality is the art of living in the present moment.",
        "The best way to predict the future is to create it.",
        "Spirituality is the art of letting go.",
        "The more you give, the more you receive.",
        "Spirituality is the art of being.",
        "The best way to find peace is to become peace.",
        "Spirituality is the art of loving unconditionally.",
        "The more you love, the more you live.",
        "Spirituality is the art of trusting the process.",
        "The best way to find happiness is to give happiness.",
        "Spirituality is the art of being grateful.",
        "The more you thank life, the more life thanks you.",
        "Spirituality is the art of being present.",
        "The best way to find joy is to share joy.",
        "Spirituality is the art of being kind.",
        "The more you give kindness, the more you receive kindness.",
        "Spirituality is the art of being compassionate.",
        "The best way to find love is to be love.",
        "Spirituality is the art of being patient.",
        "The more you wait, the more you receive."
    ],
    
    "humor": [
        "Laughter is the best way to say thank you—don’t hear others.",  
        "Life is short. Smile while you still have teeth.",  
        "I’m not lazy, I’m in energy-saving mode.",  
        "I put the ‘pro’ in procrastination.",  
        "My bed is a magical place where I suddenly remember everything I must do.",  
        "I’m not arguing, I’m just explaining why I’m right.",  
        "I don’t need therapy. I just need to win the lottery.",  
        "I’m not a complete idiot—some parts are missing.",  
        "I’m not shy. I’m just better at listening than talking.",  
        "I’m not a morning person. If I were, I’d be a unicorn.",  
        "I don’t hold grudges. I remember facts.",  
        "I’m not short. I’m concentrated awesome.",  
        "I’m not ignoring you. I’m just prioritizing my peace.",  
        "I’m not late. Everyone else is just early.",  
        "I’m not a control freak. I just like things done my way.",  
        "I’m not a hoarder. I’m a collector of potential.",  
        "I’m not a snack. I’m the whole damn meal.",  
        "I’m not a drama queen. I’m a drama empress.",  
        "I’m not a mess. I’m a creative disaster.",  
        "I’m not a failure. I’m a success at finding what doesn’t work.",  
        "I’m not a pessimist. I’m a realist with high standards.",  
        "I’m not a workaholic. I’m a work enthusiast.",  
        "I’m not a night owl. I’m a permanently exhausted pigeon.",  
        "I’m not a morning person. I’m a coffee-powered zombie.",  
        "I’m not a people person. I’m a dog person.",  
        "I’m not a perfectionist. I’m a ‘why settle for less’-ist.",  
        "I’m not a troublemaker. I’m a creative problem solver.",  
        "I’m not a know-it-all. I’m just always right.",  
        "I’m not a bad influence. I’m a fun architect.",  
        "I’m not a quitter. I’m a ‘this is boring’-ist.",  
        "I’m not a morning person. I’m a ‘why is the sun so loud?’-ist."  
    ],
    
    "existential": [
        "The universe whispered: ‘You are stardust with anxiety’.",
        "We’re all just ghosts with expiration dates.",
        "Life isn’t a puzzle to solve. It’s a dance to mess up.",
        "You’re not lost. You’re in beta testing.",
        "The meaning of life? Wrong question. Create your own.",
        "You’re not a drop in the ocean. You’re the ocean in a drop.",
        "Existence is chaos with WiFi.",
        "You don’t find yourself. You build yourself.",
        "The cosmos doesn’t care. That’s your superpower.",
        "Reality is a collective hallucination with taxes.",
        "You’re not failing. You’re collecting data for enlightenment.",
        "Time is an illusion. Deadlines are not.",
        "The only ‘afterlife’ that matters is the impact you leave.",
        "You’re not a human being. You’re a universe experiencing itself.",
        "Free will is realizing you’re the scriptwriter of your own delusion.",
        "The purpose of life? To uninstall societal programming.",
        "You’re not broken. You’re a glitch in the matrix.",
        "Enlightenment is realizing there’s no finish line.",
        "The answer to ‘why?’ is ‘why not?’",
        "You’re not a soul trapped in a body. You’re a body trapped in time.",
        "The only ‘destiny’ is the one you consent to.",
        "Reincarnation is real – you wake up as a new version of yourself daily.",
        "The universe didn’t abandon you. It’s waiting for your move.",
        "You’re not seeking purpose. You’re avoiding boredom.",
        "The void stares back. Wink at it.",
        "Your existence is statistically impossible. Act accordingly.",
        "Death isn’t the end. It’s the ultimate ‘skip ad’ button.",
        "You’re not a passenger. You’re the driver of a stolen spaceship.",
        "The meaning of life? ‘404 Error: Create Your Own’.",
        "You’re not a mistake. You’re a cosmic inside joke."
    ],
    
    "dark_motivation": [
        "The world doesn’t want you to win. Prove it wrong.",
        "Your comfort zone is a graveyard for potential.",
        "Pain is just weakness leaving the body. Scream thank you.",
        "The only therapy you need is relentless action.",
        "Your trauma isn’t your fault. Your comeback is your responsibility.",
        "The devil whispered: ‘You can’t withstand the storm.’ I whispered back: ‘I am the storm.’",
        "Your rock bottom is the foundation you’ll rebuild from.",
        "Suffering is optional. Success is mandatory.",
        "The fire that melts others forges you.",
        "Your haters are your unpaid motivators.",
        "The world breaks everyone. Some become stronger at the broken places.",
        "Your fears are liars. Your pain is a teacher.",
        "You’re not drowning. You’re being baptized in struggle.",
        "The darkest nights produce the brightest stars.",
        "Your scars are proof you outlived your doubts.",
        "The weight you carry is building muscles you’ll need later.",
        "Your breakdown is the prelude to your breakthrough.",
        "The monster under your bed is you – untamed potential.",
        "Your suffering isn’t pointless. It’s preparation.",
        "The universe doesn’t test you. It trains you.",
        "Your wounds are where the light enters. Bleed brilliance.",
        "The pain of discipline hurts less than the pain of regret.",
        "Your struggles are the setup for your comeback story.",
        "The phoenix must burn to rise. Let it burn.",
        "Your obstacles aren’t blocking you – they’re directing you.",
        "The battle isn’t against others. It’s against the weaker version of yourself.",
        "Your failures aren’t losses. They’re tuition fees.",
        "The climb is brutal. The view is worth it.",
        "Your resistance is the measure of your growth.",
        "The end of your comfort zone is the start of your legacy."
    ],

    "gym_rat": [
        "The only cheat day I know is cheating death.",
        "Your warm-up is my cool-down.",
        "The scale lies. The barbell doesn’t.",
        "Sweat is just fat crying.",
        "Your excuses are my warm-up weights.",
        "The only light here is your workout intensity.",
        "My rest days are just active recovery.",
        "The pain you feel today is the strength you’ll feel tomorrow.",
        "Your I can’t is my watch me.",
        "The gym doesn’t have mirrors because you’re here to work, not pose.",
        "My gym bag is heavier than your willpower.",
        "The only supplement I need is discipline.",
        "Your good enough is my warm-up.",
        "The only muscle I flex is my work ethic.",
        "My workout playlist is just metal and spite.",
        "The only off season I know is off the couch.",
        "Your max is my warm-up.",
        "The only failure is not showing up.",
        "My gym crush is the next PR.",
        "The only easy day was yesterday.",
        "Your tired is my just getting started.",
        "The only break I take is between sets.",
        "My rest day is your leg day.",
        "The only cheat meal I know is extra protein.",
        "Your no pain, no gain is my pain is the gain.",
        "The only overtraining I fear is undertraining.",
        "My gym shoes have more miles than your car.",
        "The only bad form is not showing up.",
        "Your I’ll start tomorrow’ is my I never stopped.",
        "The only limit is the one you set."
    ],
    
    "alpha": [
        "The lion doesn’t lose sleep over the opinions of sheep.",
        "Your comfort zone is my hunting ground.",
        "The pack follows. The leader hunts alone.",
        "Don’t chase. Attract.",
        "The weak seek permission. The strong take action.",
        "Your no is my next.",
        "The herd grazes. The alpha feasts.",
        "Don’t compete. Dominate.",
        "The rules don’t apply to those who make them.",
        "Your doubts are my stepping stones.",
        "The beta asks why?. The alpha says watch me.",
        "Don’t explain. Execute.",
        "The weak adapt. The strong redefine.",
        "Your limits are my warm-up.",
        "The follower needs a map. The leader draws it.",
        "Don’t beg. Deserve.",
        "The prey runs. The predator strategizes.",
        "Your impossible is my already done.",
        "The sheep votes. The lion eats the sheep.",
        "Don’t hope. Rnsure.",
        "The weak fear the storm. The strong ride it.",
        "Your can’t is my already did.",
        "The follower waits for luck. The leader creates it.",
        "Don’t follow trends. Set them.",
        "The weak seek validation. The strong validate themselves.",
        "Your maybe is my done.",
        "The beta complains. The alpha conquers.",
        "Don’t ask for opportunities. Create them.",
        "The weak need motivation. The strong are the motivation.",
        "Your someday is my today."
    ],
    
    "glow_up": [
        "Your future self is watching. Make is great.",
        "The glow up isn’t just physical. It’s financial, emotional, and spiritual.",
        "Your before picture is someone else’s goal.",
        "The best revenge is a killer glow up.",
        "Your haters are your cheapest motivators.",
        "The glow up starts when the self-pity stops.",
        "Your excuses won’t look good in the after photos.",
        "The mirror doesn’t lie. Your sweat does.",
        "Your I can’t is your old self talking.",
        "The glow up isn’t a moment. It’s a mindset.",
        "Your struggles are just plot twists in your glow up story.",
        "The only filter you need is discipline.",
        "Your too hard is your not yet.",
        "The glow up isn’t pretty. The results are.",
        "Your comfort zone is where glow ups go to die.",
        "The only quick fix is hard work.",
        "Your past is just prologue. The glow up is the main story.",
        "The mirror reflects. Your actions project.",
        "Your someday is today.",
        "The glow up isn’t linear. But it’s inevitable.",
        "Your doubts are just noise. Your grind is the signal.",
        "The only overnight success is years in the making.",
        "Your why me? becomes try me.",
        "The glow up isn’t luck. It’s labor.",
        "Your starting tomorrow is your biggest enemy.",
        "The only magic pill is persistence.",
        "Your future self thanks you for starting now.",
        "The glow up isn’t vanity. It’s victory.",
        "Your I’ll try becomes I did.",
        "The only secret is you vs. you."
    ],
    
    "silent_killer": [
        "The loudest one in the room is the weakest. I speak through results.",
        "Your noise is my mute button.",
        "The grind doesn’t need a soundtrack.",
        "Don’t announce moves. Drop results.",
        "Your hype is my distraction.",
        "The silent wolf hunts best.",
        "Don’t post goals. Post receipts.",
        "Your applause is my background noise.",
        "The quietest grind makes the loudest impact.",
        "Don’t need a spotlight. Create my own light.",
        "Your talk is cheap. My work is currency.",
        "The strongest storms start in silence.",
        "Don’t compete. I outwork.",
        "Your excuses are my fuel.",
        "The masterpiece isn’t painted with words.",
        "Don’t explain. My results do.",
        "Your doubts are my warm-up.",
        "The lion doesn’t roar when hunting.",
        "Don’t seek attention. Command it.",
        "Your overnight success is my years of silence.",
        "The best revenge is no explanation. Just success.",
        "Don’t break promises. Dreak records.",
        "Your noise is my meditation.",
        "The quietest ones have the deadliest focus.",
        "Don’t follow trends. Set them quietly.",
        "Your viral is my irrelevant.",
        "The strongest foundations are poured in silence.",
        "you don’t need motivation. You are the motivation.",
        "Your look at me is my watch me.",
        "The silent grind is the deadliest."
    ],
    
    "unstoppable": [
        "The only exit in my plan is execute.",
        "Your plan B is my distraction.",
        "The unstoppable don’t have backups. They have breakthroughs.",
        "Don’t pivot. Plow through.",
        "Your what ifs are my what’s next.",
        "The obstacle is the way. I am the bulldozer.",
        "Don’t retreat. Reload.",
        "Your doubts are my stepping stones.",
        "The unstoppable don’t wait for permission. They take territory.",
        "Don’t slow down. Speed up.",
        "Your too hard is my just right.",
        "The only no I accept is no limits.",
        "Don’t hesitate. Dominate.",
        "Your fear is my playground.",
        "The unstoppable don’t complain. They conquer.",
        "Don’t need luck. Create momentum.",
        "Your impossible is my already done.",
        "The only failure is quitting.",
        "Don’t stop. Level up.",
        "Your can’t is my watch me.",
        "The unstoppable don’t break. They bend reality.",
        "Don’t doubt. Do.",
        "Your maybe is my done.",
        "The only wall is the one you build yourself.",
        "Don’t fear resistance. Are the resistance.",
        "Your someday is my today.",
        "The unstoppable don’t wait for the storm to pass. They dance in it.",
        "Don’t follow paths. Create them.",
        "Your what if I fail? is my what if I fly?",
        "The only end is the one I choose."
    ],
    
    "can’t": [
        "You don’t stop when you’re tired. You stop when you’re done.",  
        "You think you can’t? Look how far you’ve already come.",  
        "You’re stronger than your excuses.",  
        "You didn’t come this far to only come this far.",  
        "You fear the pain? The regret will hurt worse.",  
        "You want to quit? Remember why you started.",  
        "You’re not stuck. You’re just preparing for the leap.",  
        "You feel the burn? That’s weakness leaving your body.",  
        "You think it’s impossible? Someone else is doing it right now.",  
        "You’re not a quitter. You’re a fighter.",  
        "You have two choices: give up or prove them wrong.",  
        "You don’t need motivation. You need discipline.",  
        "You’re not failing. You’re learning how to win.",  
        "You feel like collapsing? The breakthrough is coming.",  
        "You’re not alone in the struggle. But you’ll stand alone in the victory.",  
        "You think you’re weak? Your mind is lying to you.",  
        "You want to rest? The competition isn’t sleeping.",  
        "You’re not broken. You’re being rebuilt.",  
        "You doubt yourself? Your potential disagrees.",  
        "You feel the pressure? That’s how diamonds are made.",  
        "You’re not losing. You’re grinding.",  
        "You think it’s too hard? The easy path leads to nowhere.",  
        "You’re tired? Good. That means you’re pushing limits.",  
        "You want to slow down? Your future self is begging you to keep going.",  
        "You feel like giving up? That’s the moment champions are made.",  
        "You think you’re not enough? You’re more than enough.",  
        "You’re scared? Fear is just excitement without breath.",  
        "You’re not a victim. You’re a warrior.",  
        "You think it’s too late? The best time to start was yesterday. The second best is now.",  
        "You can’t see the finish line? Trust the process."  
    ]
}