motivational_quotes = {
    # Mental Toughness (30 quotes)
    "mental_toughness": [
        "Mental toughness is when you do it even when your brain screams stop.",
        "The mind quits 1000x before the body does.",
        "Discomfort is the price of admission to an extraordinary life.",
        "You don't get mental strength - you earn it through suffering.",
        "The best mental state? 'Fuck it, let's go.'",
        "Your worst day is someone else's dream workout.",
        "Pain is temporary. Quitting lasts forever.",
        "The voice that says 'you can't' is a liar. Prove it wrong.",
        "Champions are just people who refused to give up.",
        "When you want to quit, that's when the game begins.",
        "No one is coming to save you. Save yourself.",
        "The harder the grind, the brighter the shine.",
        "Tough times don't last. Tough people do.",
        "Pressure makes diamonds. Embrace the squeeze.",
        "The difference between ordinary and extraordinary is that little 'extra'.",
        "If it doesn't challenge you, it won't change you.",
        "The only easy day was yesterday.",
        "Sweat is just weakness leaving the body.",
        "You can either suffer the pain of discipline or the pain of regret.",
        "The body achieves what the mind believes.",
        "Excuses sound best to those who make them.",
        "The only limit is the one you set yourself.",
        "Get comfortable being uncomfortable.",
        "Winners do what losers won't.",
        "Your comfort zone is where dreams go to die.",
        "The burn means it's working.",
        "Don't stop when you're tired. Stop when you're done.",
        "The strongest steel is forged in the hottest fire.",
        "No resistance, no strength.",
        "The obstacle is the way."
    ],

    # Hustle & Grind (30 quotes)
    "hustle": [
        "While you're sleeping, someone's outworking you.",
        "Hustle beats talent when talent doesn't hustle.",
        "The grind doesn't stop. Neither should you.",
        "No days off isn't a slogan - it's a lifestyle.",
        "You either find a way or make one.",
        "The secret? Work while they sleep.",
        "Your 9-5 is someone else's warm-up.",
        "The extra mile is never crowded.",
        "Weekends are for amateurs.",
        "Burn the midnight oil while others burn time.",
        "Hustle in silence. Let success make the noise.",
        "Dreams don't work unless you do.",
        "The elevator to success is out of order. Take the stairs.",
        "Wake up with determination. Go to bed with satisfaction.",
        "Success is nothing more than a few simple disciplines, practiced every day.",
        "The only place success comes before work is in the dictionary.",
        "Grind now. Shine later.",
        "You'll never regret the work you did today.",
        "The difference between who you are and who you want to be is what you do.",
        "Small daily improvements lead to staggering long-term results.",
        "Don't watch the clock; do what it does. Keep going.",
        "The only thing standing between you and your goal is the story you keep telling yourself.",
        "Success isn't owned. It's leased. And rent is due every day.",
        "The road to success is always under construction.",
        "Opportunities don't happen. You create them.",
        "Work until your idols become your rivals.",
        "The only thing overworking leads to is more success.",
        "Your future is created by what you do today, not tomorrow.",
        "The grind is the glory.",
        "No one ever drowned in sweat."
    ],

    # Success Principles (30 quotes)
    "success": [
        "Success leaves clues. Follow the patterns.",
        "The compound effect: Small actions, massive results.",
        "You're the average of the 5 people you tolerate.",
        "What you tolerate, you attract more of.",
        "Your network determines your net worth.",
        "Money flows to value. Create more value.",
        "The rich solve problems. The poor complain about them.",
        "Wealth isn't about money - it's about options.",
        "Opportunities multiply as they are seized.",
        "Profit is better than wages. Equity is better than both.",
        "Success is the sum of small efforts repeated daily.",
        "The secret of getting ahead is getting started.",
        "Don't wish it were easier. Wish you were better.",
        "The only thing worse than starting something and failing is not starting something.",
        "Successful people do what unsuccessful people are unwilling to do.",
        "Your level of success will rarely exceed your level of personal development.",
        "Success is walking from failure to failure with no loss of enthusiasm.",
        "The expert in anything was once a beginner.",
        "Success is not final, failure is not fatal: It is the courage to continue that counts.",
        "The only limit to our realization of tomorrow will be our doubts of today.",
        "Success usually comes to those who are too busy to be looking for it.",
        "The way to get started is to quit talking and begin doing.",
        "Success seems to be connected with action. Successful people keep moving.",
        "There are no shortcuts to any place worth going.",
        "Success is where preparation and opportunity meet.",
        "The successful warrior is the average man, with laser-like focus.",
        "Success is not the key to happiness. Happiness is the key to success.",
        "Successful people have fear, successful people have doubts, and successful people have worries.",
        "Success is getting what you want. Happiness is wanting what you get.",
        "The price of success is hard work, dedication to the job at hand."
    ],

    # Failure & Growth (30 quotes)
    "failure": [
        "Fail faster. Learn quicker.",
        "Every no gets you closer to a hell yes.",
        "Rejection is redirection.",
        "The master has failed more times than the beginner has tried.",
        "Your worst failures make the best stories.",
        "Scars prove you showed up to fight.",
        "Smooth seas don't make skilled sailors.",
        "If it doesn't challenge you, it won't change you.",
        "Breakdowns lead to breakthroughs.",
        "The obstacle is the way.",
        "Failure is simply the opportunity to begin again, this time more intelligently.",
        "I have not failed. I've just found 10,000 ways that won't work.",
        "Failure is the condiment that gives success its flavor.",
        "There is no failure except in no longer trying.",
        "Failure is not the opposite of success; it's part of success.",
        "Success is stumbling from failure to failure with no loss of enthusiasm.",
        "You build on failure. You use it as a stepping stone.",
        "The only real mistake is the one from which we learn nothing.",
        "Failure is the tuition you pay for success.",
        "Don't fear failure. Fear being in the exact same place next year.",
        "Failure is not fatal, but failure to change might be.",
        "Failure is only the opportunity to begin again more intelligently.",
        "Our greatest glory is not in never falling, but in rising every time we fall.",
        "A man's errors are his portals of discovery.",
        "You may encounter many defeats, but you must not be defeated.",
        "Failure is the opportunity to begin again more intelligently.",
        "The phoenix must burn to emerge.",
        "Every adversity, every failure, every heartache carries with it the seed of an equal or greater benefit.",
        "Rock bottom became the solid foundation on which I rebuilt my life.",
        "Sometimes you win, sometimes you learn."
    ],

    # Mindset Shifts (30 quotes)
    "mindset": [
        "Poverty is a mindset before it's a bank balance.",
        "Your income is directly tied to your self-image.",
        "What you walk past is what you accept.",
        "Victim mentality is the ultimate success killer.",
        "The moment you take full responsibility is when real growth begins.",
        "Excuses are the nails that build the house of failure.",
        "Your biggest limitation is the story you tell yourself.",
        "Confidence is earned through demonstrated competence.",
        "Self-doubt is the tax on dreams. Stop paying it.",
        "The only permission you need is your own.",
        "Whether you think you can or you think you can't, you're right.",
        "The mind is everything. What you think you become.",
        "Change your thoughts and you change your world.",
        "We are what we repeatedly do. Excellence, then, is not an act, but a habit.",
        "The only way to do great work is to love what you do.",
        "Your attitude, not your aptitude, will determine your altitude.",
        "The greatest discovery of all time is that a person can change his future by merely changing his attitude.",
        "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.",
        "Life is 10% what happens to you and 90% how you react to it.",
        "You cannot always control what goes on outside. But you can always control what goes on inside.",
        "The secret of change is to focus all of your energy, not on fighting the old, but on building the new.",
        "What lies behind us and what lies before us are tiny matters compared to what lies within us.",
        "It's not the load that breaks you down, it's the way you carry it.",
        "You are never too old to set another goal or to dream a new dream.",
        "The only person you are destined to become is the person you decide to be.",
        "The greatest weapon against stress is our ability to choose one thought over another.",
        "Happiness is not something ready made. It comes from your own actions.",
        "The mind is not a vessel to be filled, but a fire to be kindled.",
        "You have power over your mind - not outside events. Realize this, and you will find strength.",
        "The happiness of your life depends upon the quality of your thoughts."
    ],

    # Warrior Mentality (30 quotes)
    "warrior": [
        "Warriors choose discipline over dopamine.",
        "The battle is won in the mind before it's fought in reality.",
        "A lion doesn't concern himself with the opinions of sheep.",
        "Iron sharpens iron. Surround yourself with killers.",
        "Weakness is a choice. Strength is earned.",
        "A warrior's rest comes after the victory, not before.",
        "The difference between a hero and coward is one decision.",
        "Fear is the compass pointing to where you must go.",
        "Comfort is the enemy of achievement.",
        "Suffer the pain of discipline or suffer the pain of regret.",
        "The warrior's greatest weapon is his mind.",
        "A warrior is not defined by his strength but by his resilience.",
        "The warrior's path is walked alone, but never lonely.",
        "A warrior's strength comes from overcoming what he thought he couldn't.",
        "The warrior knows that pain is temporary but quitting lasts forever.",
        "A true warrior fights not because he hates what is in front of him, but because he loves what is behind him.",
        "The warrior's creed: Never give up, never give in.",
        "A warrior's greatest battle is the one within.",
        "The warrior does not pray for an easy life, but for the strength to endure a difficult one.",
        "A warrior's spirit cannot be broken, only tempered.",
        "The warrior knows that fear is just a feeling, not a fact.",
        "A warrior's discipline is his freedom.",
        "The warrior understands that struggle is the path to mastery.",
        "A warrior's greatest enemy is not the opponent before him, but the doubt within him.",
        "The warrior's code: Honor, courage, commitment.",
        "A warrior does not seek conflict, but he does not fear it.",
        "The warrior's journey is not to defeat others, but to conquer himself.",
        "A warrior's rest is earned, not given.",
        "The warrior knows that every scar tells a story of survival.",
        "A warrior's legacy is not in the battles he won, but in the lives he inspired."
    ],

    # Business & Money (30 quotes)
    "business": [
        "Revenue solves all problems. Focus there first.",
        "Profitability = freedom. Losses = slavery.",
        "Business isn't complicated - create more value than you capture.",
        "The market doesn't care about your feelings. Deliver or die.",
        "Raise prices. Fire bad clients. Work less, earn more.",
        "Time poverty is worse than money poverty. Fix both.",
        "Wealth is created in leverage - time, money, or attention.",
        "Money follows speed. Execute faster.",
        "The best business strategy? Outlast everyone else.",
        "Monetize your knowledge. Package your experience.",
        "The best investment you can make is in yourself.",
        "Money is a great servant but a terrible master.",
        "The rich invest their time and money. The poor spend theirs.",
        "Formal education will make you a living; self-education will make you a fortune.",
        "The single most powerful asset we all have is our mind.",
        "It's not how much money you make, but how much money you keep.",
        "The more you learn, the more you earn.",
        "Opportunities are never lost; someone will take the ones you miss.",
        "The biggest risk is not taking any risk.",
        "Price is what you pay. Value is what you get.",
        "The stock market is a device for transferring money from the impatient to the patient.",
        "Risk comes from not knowing what you're doing.",
        "The most important investment you can make is in yourself.",
        "Never depend on single income. Make investment to create a second source.",
        "If you don't find a way to make money while you sleep, you will work until you die.",
        "The goal isn't more money. The goal is living life on your terms.",
        "Money is only a tool. It will take you wherever you wish, but it will not replace you as the driver.",
        "Financial peace isn't the acquisition of stuff. It's learning to live on less than you make.",
        "An investment in knowledge pays the best interest.",
        "The art is not in making money, but in keeping it."
    ],

    # Life Truths (30 quotes)
    "life": [
        "No one cares. Produce results anyway.",
        "The universe rewards boldness.",
        "Your life is the sum of your standards.",
        "What you avoid controls you.",
        "Character is what you do when no one's watching.",
        "Legacy > Likes.",
        "Hard choices, easy life. Easy choices, hard life.",
        "The price of anything is the life you exchange for it.",
        "Time is the only non-renewable resource. Spend it wisely.",
        "Death is coming. What will you have to show for your time here?",
        "Life is 10% what happens to you and 90% how you react to it.",
        "The purpose of our lives is to be happy.",
        "Life is what happens when you're busy making other plans.",
        "Get busy living or get busy dying.",
        "You only live once, but if you do it right, once is enough.",
        "The unexamined life is not worth living.",
        "Turn your wounds into wisdom.",
        "Live as if you were to die tomorrow. Learn as if you were to live forever.",
        "The two most important days in your life are the day you are born and the day you find out why.",
        "Life is not a problem to be solved, but a reality to be experienced.",
        "The best way to predict your future is to create it.",
        "Life is really simple, but we insist on making it complicated.",
        "The biggest adventure you can take is to live the life of your dreams.",
        "Life shrinks or expands in proportion to one's courage.",
        "Don't count the days, make the days count.",
        "Life is either a daring adventure or nothing at all.",
        "The good life is one inspired by love and guided by knowledge.",
        "Life isn't about finding yourself. Life is about creating yourself.",
        "The meaning of life is to give life meaning.",
        "Life is short, and it's up to you to make it sweet."
    ],

    # Discipline (30 quotes)
    "discipline": [
        "Discipline is choosing between what you want now and what you want most.",
        "Discipline is the bridge between goals and accomplishment.",
        "With self-discipline most anything is possible.",
        "Discipline is doing what needs to be done even when you don't want to do it.",
        "Small disciplines repeated with consistency every day lead to great achievements.",
        "Discipline is the soul of an army. It makes small numbers formidable.",
        "The pain of discipline weighs ounces. The pain of regret weighs tons.",
        "Discipline is remembering what you want.",
        "Discipline is the foundation upon which all success is built.",
        "Without discipline, there's no life at all.",
        "Discipline is the refining fire by which talent becomes ability.",
        "Discipline is the difference between wishing for something and getting it.",
        "Self-discipline begins with the mastery of your thoughts.",
        "Discipline is the mother of good fortune.",
        "Discipline is the strongest form of self-love.",
        "Discipline is the key to unlocking your potential.",
        "Discipline is the habit of taking consistent action.",
        "Discipline is the compass that guides you to your goals.",
        "Discipline is the art of making yourself do what you know needs to be done.",
        "Discipline is the fuel for achievement.",
        "Discipline is the root of all virtues.",
        "Discipline is the soul of success.",
        "Discipline is the master key to riches.",
        "Discipline is the ability to make yourself do what you should do, when you should do it.",
        "Discipline is the difference between a dream and a goal.",
        "Discipline is the path to freedom.",
        "Discipline is the secret ingredient to success.",
        "Discipline is the ability to give up excuses.",
        "Discipline is the strength to resist temptations.",
        "Discipline is the power to say no to distractions."
    ],

    # motivational_quotes (30 quotes)
    "motivational_quotes": [
        "motivational_quotes is what gets you started. Habit is what keeps you going.",
        "People often say that motivational_quotes doesn't last. Well, neither does bathing - that's why we recommend it daily.",
        "The only way to do great work is to love what you do.",
        "Your time is limited, so don't waste it living someone else's life.",
        "The future belongs to those who believe in the beauty of their dreams.",
        "The only limit to our realization of tomorrow is our doubts of today.",
        "Don't watch the clock; do what it does. Keep going.",
        "You miss 100% of the shots you don't take.",
        "The secret of getting ahead is getting started.",
        "Believe you can and you're halfway there.",
        "It always seems impossible until it's done.",
        "Start where you are. Use what you have. Do what you can.",
        "The best way to predict the future is to create it.",
        "Success is not the key to happiness. Happiness is the key to success.",
        "The only person you are destined to become is the person you decide to be.",
        "What you get by achieving your goals is not as important as what you become by achieving your goals.",
        "You are never too old to set another goal or to dream a new dream.",
        "The journey of a thousand miles begins with one step.",
        "Dream big and dare to fail.",
        "You don't have to be great to start, but you have to start to be great.",
        "The only thing standing between you and your goal is the story you keep telling yourself.",
        "Success is walking from failure to failure with no loss of enthusiasm.",
        "The expert in anything was once a beginner.",
        "Don't be pushed around by the fears in your mind. Be led by the dreams in your heart.",
        "The harder you work for something, the greater you'll feel when you achieve it.",
        "Push yourself, because no one else is going to do it for you.",
        "Great things never come from comfort zones.",
        "Dream it. Believe it. Build it.",
        "The secret to getting ahead is getting started.",
        "Don't stop when you're tired. Stop when you're done."
    ]
}